### Crear alumno aprobado
POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "nombre": "joel",
    "notas": [7, 8, 6]
}

### Crear alumno reprobado
POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "nombre": "pedro",
    "notas": [1, 8, 8]
}

### Crear alumno promocionado
POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "nombre": "maria antonia guitierrez",
    "notas": [9, 8, 8]
}

### Listar alumnos
GET http://localhost:3000/alumnos

### Consultar alumno por ID
GET http://localhost:3000/alumnos/3

### Eliminar alumno
DELETE http://localhost:3000/alumnos/3