### Crear tarea 1
POST http://localhost:3000/tareas
Content-Type: application/json

{
    "tarea": "Comprar leche",
    "completada": false
}

### Crear tarea 2
POST http://localhost:3000/tareas
Content-Type: application/json

{
    "tarea": "Hacer la tarea de matemáticas",
    "completada": false
}


### Crear tarea 3
POST http://localhost:3000/tareas
Content-Type: application/json

{
    "tarea": "Lavar el auto",
    "completada": true
}

### Listar tareas completadas
GET http://localhost:3000/tareas?completada=true

### Listar tareas no completadas
GET http://localhost:3000/tareas?completada=false

### Listar todas las tareas
GET http://localhost:3000/tareas

### Consultar tarea por ID
GET http://localhost:3000/tareas/1

### Eliminar tarea
DELETE http://localhost:3000/tareas/1