### Crear un cálculo
POST http://localhost:3000/calculos
Content-Type: application/json

{
    "base": -3,
    "altura": 3
}

### Listar cálculos
GET http://localhost:3000/calculos

### Consultar cálculo por ID
GET http://localhost:3000/calculos/1

### Eliminar un cálculo
DELETE http://localhost:3000/calculos/1